=== korteke/java-opensaml/import/java-xmltooling/trunk/src/schema/xmltooling-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
    xmlns:xt="http://www.opensaml.org/xmltooling-config"
    targetNamespace="http://www.opensaml.org/xmltooling-config">

    <element name="XMLTooling" type="xt:XMLToolingType" />
    <complexType name="XMLToolingType">
        <sequence>
            <element ref="xt:ObjectProviders" />
        </sequence>

        <attribute name="clock-skew" type="long" use="optional" />
    </complexType>

    <element name="ObjectProviders" type="xt:ObjectProvidersType" />
    <complexType name="ObjectProvidersType">
        <sequence>
            <element ref="xt:ObjectProvider" maxOccurs="unbounded" />
        </sequence>

        <attribute name="ignoreUnknownAttributes" type="boolean" use="optional" />
        <attribute name="ignoreUnknownElements" type="boolean" use="optional" default="false"/>
    </complexType>

    <element name="ObjectProvider" type="xt:ObjectProviderType" />
    <complexType name="ObjectProviderType">
        <sequence>
            <element ref="xt:BuilderClass" />
            <element ref="xt:MarshallingClass" />
            <element ref="xt:UnmarshallingClass" />
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" />
        </sequence>

        <attribute name="qualifiedName" type="QName" use="required" />
        <anyAttribute namespace="##other" />
    </complexType>

    <element name="BuilderClass" type="xt:ClassType" />
    <element name="MarshallingClass" type="xt:ClassType" />
    <element name="UnmarshallingClass" type="xt:ClassType" />
    <complexType name="ClassType">
        <sequence>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded" />
        </sequence>

        <attribute name="className" type="string" use="required" />
        <anyAttribute namespace="##other" />
    </complexType>

</schema>

=== korteke/java-opensaml/trunk/opensaml-soap-impl/src/main/resources/wssecurity-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsse11="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">

    <!-- WS-Security 2004 Object Providers -->
    <ObjectProviders>
    
        <!-- wsse:BinarySecurityToken -->
        <ObjectProvider qualifiedName="wsse:BinarySecurityToken">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.BinarySecurityTokenBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.BinarySecurityTokenMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.BinarySecurityTokenUnmarshaller"/>
        </ObjectProvider>

        <!-- wsu:Created -->
        <ObjectProvider qualifiedName="wsu:Created">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.CreatedBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.CreatedMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.CreatedUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Embedded -->
        <ObjectProvider qualifiedName="wsse:Embedded">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.EmbeddedBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.EmbeddedMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.EmbeddedUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse11:EncryptedHeader -->
        <ObjectProvider qualifiedName="wsse11:EncryptedHeader">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.EncryptedHeaderBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.EncryptedHeaderMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.EncryptedHeaderUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsu:Expires -->
        <ObjectProvider qualifiedName="wsu:Expires">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.ExpiresBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.ExpiresMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.ExpiresUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse11:Iteration -->
        <ObjectProvider qualifiedName="wsse11:Iteration">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.IterationBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.IterationMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.IterationUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:KeyIdentifier -->
        <ObjectProvider qualifiedName="wsse:KeyIdentifier">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.KeyIdentifierBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.KeyIdentifierMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.KeyIdentifierUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Nonce -->
        <ObjectProvider qualifiedName="wsse:Nonce">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.NonceBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.NonceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.NonceUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Password -->
        <ObjectProvider qualifiedName="wsse:Password">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.PasswordBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.PasswordMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.PasswordUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Reference -->
        <ObjectProvider qualifiedName="wsse:Reference">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.ReferenceBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.ReferenceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.ReferenceUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse11:Salt -->
        <ObjectProvider qualifiedName="wsse11:Salt">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.SaltBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.SaltMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.SaltUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:Security -->
        <ObjectProvider qualifiedName="wsse:Security">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.SecurityBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.SecurityMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.SecurityUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:SecurityTokenReference -->
        <ObjectProvider qualifiedName="wsse:SecurityTokenReference">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.SecurityTokenReferenceBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.SecurityTokenReferenceMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.SecurityTokenReferenceUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsu:SignatureConfirmation -->
        <ObjectProvider qualifiedName="wsu:SignatureConfirmation">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.SignatureConfirmationBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.SignatureConfirmationMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.SignatureConfirmationUnmarshaller"/>
        </ObjectProvider>

        <!-- wsu:Timestamp -->
        <ObjectProvider qualifiedName="wsu:Timestamp">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.TimestampBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.TimestampMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.TimestampUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsse:TransformationParameters -->
        <ObjectProvider qualifiedName="wsse:TransformationParameters">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.TransformationParametersBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.TransformationParametersMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.TransformationParametersUnmarshaller"/>
        </ObjectProvider>
        
        <!-- wsse:Username -->
        <ObjectProvider qualifiedName="wsse:Username">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.UsernameBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.UsernameMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.UsernameUnmarshaller"/>
        </ObjectProvider>

        <!-- wsse:UsernameToken -->
        <ObjectProvider qualifiedName="wsse:UsernameToken">
            <BuilderClass className="org.opensaml.ws.wssecurity.impl.UsernameTokenBuilder"/>
            <MarshallingClass className="org.opensaml.ws.wssecurity.impl.UsernameTokenMarshaller"/>
            <UnmarshallingClass className="org.opensaml.ws.wssecurity.impl.UsernameTokenUnmarshaller"/>
        </ObjectProvider>

    </ObjectProviders>
    
    <IDAttributes>
        <IDAttribute>wsu:Id</IDAttribute>
    </IDAttributes>

</XMLTooling>

=== korteke/java-opensaml/import/java-openws/branches/wstrustIntegration/src/main/resources/wspolicy-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns="http://www.opensaml.org/xmltooling-config">

    <!-- WS-Policy 2004 Object Providers -->
    <ObjectProviders>
    
        <!-- wsp:AppliesTo -->
        <ObjectProvider qualifiedName="wsp:AppliesTo">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.AppliesToBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.AppliesMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.AppliesUnmarshaller" />
        </ObjectProvider>

        <!-- wsp:Policy -->
        <ObjectProvider qualifiedName="wsp:Policy">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.PolicyBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyUnmarshaller" />
        </ObjectProvider>

        <!-- wsp:PolicyReference -->
        <ObjectProvider qualifiedName="wsp:PolicyReference">
            <BuilderClass
                className="org.opensaml.ws.wspolicy.impl.PolicyReferenceBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyReferenceMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wspolicy.impl.PolicyReferenceUnmarshaller" />
        </ObjectProvider>

    </ObjectProviders>

</XMLTooling>

=== korteke/java-opensaml/import/java-xmltooling/trunk/test/conf/encryption-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd"
 xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
 xmlns="http://www.opensaml.org/xmltooling-config">
    
    <ObjectProviders>
    
        <!-- XML Encryption EncryptedData -->
        <ObjectProvider qualifiedName="xenc:EncryptedData">
            <BuilderClass className="org.opensaml.xml.encryption.impl.EncryptedDataBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.EncryptedDataMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.EncryptedDataUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption EncryptedKey -->
        <ObjectProvider qualifiedName="xenc:EncryptedKey">
            <BuilderClass className="org.opensaml.xml.encryption.impl.EncryptedKeyBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.EncryptedKeyMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.EncryptedKeyUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption KeySize -->
        <ObjectProvider qualifiedName="xenc:KeySize">
            <BuilderClass className="org.opensaml.xml.encryption.impl.KeySizeBuilder" />
            <MarshallingClass className="org.opensaml.xml.schema.impl.XSIntegerMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.schema.impl.XSIntegerUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption OAEPparams -->
        <ObjectProvider qualifiedName="xenc:OAEPparams">
            <BuilderClass className="org.opensaml.xml.encryption.impl.OAEPparamsBuilder" />
            <MarshallingClass className="org.opensaml.xml.schema.impl.XSBase64BinaryMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.schema.impl.XSBase64BinaryUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption CipherValue -->
        <ObjectProvider qualifiedName="xenc:CipherValue">
            <BuilderClass className="org.opensaml.xml.encryption.impl.CipherValueBuilder" />
            <MarshallingClass className="org.opensaml.xml.schema.impl.XSBase64BinaryMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.schema.impl.XSBase64BinaryUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption KANonce -->
        <ObjectProvider qualifiedName="xenc:KA-Nonce">
            <BuilderClass className="org.opensaml.xml.encryption.impl.KANonceBuilder" />
            <MarshallingClass className="org.opensaml.xml.schema.impl.XSBase64BinaryMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.schema.impl.XSBase64BinaryUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption EncryptionMethod -->
        <ObjectProvider qualifiedName="xenc:EncryptionMethod">
            <BuilderClass className="org.opensaml.xml.encryption.impl.EncryptionMethodBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.EncryptionMethodMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.EncryptionMethodUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption Transforms -->
        <ObjectProvider qualifiedName="xenc:Transforms">
            <BuilderClass className="org.opensaml.xml.encryption.impl.TransformsBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.TransformsMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.TransformsUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption CipherReference -->
        <ObjectProvider qualifiedName="xenc:CipherReference">
            <BuilderClass className="org.opensaml.xml.encryption.impl.CipherReferenceBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.CipherReferenceMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.CipherReferenceUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption DataReference -->
        <ObjectProvider qualifiedName="xenc:DataReference">
            <BuilderClass className="org.opensaml.xml.encryption.impl.DataReferenceBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.DataReferenceMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.DataReferenceUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption KeyReference -->
        <ObjectProvider qualifiedName="xenc:KeyReference">
            <BuilderClass className="org.opensaml.xml.encryption.impl.KeyReferenceBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.KeyReferenceMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.KeyReferenceUnmarshaller" />
        </ObjectProvider>
        
        <!-- XML Encryption ReferenceList -->
        <ObjectProvider qualifiedName="xenc:ReferenceList">
            <BuilderClass className="org.opensaml.xml.encryption.impl.ReferenceListBuilder" />
            <MarshallingClass className="org.opensaml.xml.encryption.impl.ReferenceListMarshaller" />
            <UnmarshallingClass className="org.opensaml.xml.encryption.impl.ReferenceListUnmarshaller" />
        </ObjectProvider>
        
    </ObjectProviders>

</XMLTooling>

=== korteke/java-opensaml/trunk/opensaml-saml-impl/src/main/resources/saml2-ecp-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecp="urn:oasis:names:tc:SAML:2.0:profiles:SSO:ecp" xmlns="http://www.opensaml.org/xmltooling-config" xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd">
 
    <!-- SAML 2.0 ECP Object providers -->
    <ObjectProviders>
        
        <!-- Request -->
        <ObjectProvider qualifiedName="ecp:Request">
            <BuilderClass className="org.opensaml.saml2.ecp.impl.RequestBuilder"/>
            <MarshallingClass className="org.opensaml.saml2.ecp.impl.RequestMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml2.ecp.impl.RequestUnmarshaller"/>
        </ObjectProvider>
        
        <!-- Response -->
        <ObjectProvider qualifiedName="ecp:Response">
            <BuilderClass className="org.opensaml.saml2.ecp.impl.ResponseBuilder"/>
            <MarshallingClass className="org.opensaml.saml2.ecp.impl.ResponseMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml2.ecp.impl.ResponseUnmarshaller"/>
        </ObjectProvider>
        
        <!-- RelayState -->
        <ObjectProvider qualifiedName="ecp:RelayState">
            <BuilderClass className="org.opensaml.saml2.ecp.impl.RelayStateBuilder"/>
            <MarshallingClass className="org.opensaml.saml2.ecp.impl.RelayStateMarshaller"/>
            <UnmarshallingClass className="org.opensaml.saml2.ecp.impl.RelayStateUnmarshaller"/>
        </ObjectProvider>
 
    </ObjectProviders>
 </XMLTooling>

=== korteke/java-opensaml/import/java-openws/branches/wstrustIntegration/resources/classpath/wsaddressing-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLTooling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.opensaml.org/xmltooling-config ../../src/schema/xmltooling-config.xsd"
    xmlns:wsa="http://www.w3.org/2005/08/addressing"
    xmlns="http://www.opensaml.org/xmltooling-config">

    <!-- WS-Addressing 1.0 Object Providers -->
    <ObjectProviders>
    
        <!-- wsa:Action -->
        <ObjectProvider qualifiedName="wsa:Action">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.ActionBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ActionMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ActionUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:Address -->
        <ObjectProvider qualifiedName="wsa:Address">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.AddressBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.AddressMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.AddressUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:EndpointReference -->
        <ObjectProvider qualifiedName="wsa:EndpointReference">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.EndpointReferenceBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.EndpointReferenceMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.EndpointReferenceUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:Metadata -->
        <ObjectProvider qualifiedName="wsa:Metadata">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.MetadataBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.MetadataMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.MetadataUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:ReferenceParameters -->
        <ObjectProvider qualifiedName="wsa:ReferenceParameters">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.ReferenceParametersBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ReferenceParametersMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ReferenceParametersUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:From -->
        <ObjectProvider qualifiedName="wsa:From">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.FromBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.FromMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.FromUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:To -->
        <ObjectProvider qualifiedName="wsa:To">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.ToBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ToMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ToUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:MessageID -->
        <ObjectProvider qualifiedName="wsa:MessageID">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.MessageIDBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.MessageIDMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.MessageIDUnmarshaller" />
        </ObjectProvider>

        <!-- wsa:ReplyTo -->
        <ObjectProvider qualifiedName="wsa:ReplyTo">
            <BuilderClass
                className="org.opensaml.ws.wsaddressing.impl.ReplyToBuilder" />
            <MarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ReplyToMarshaller" />
            <UnmarshallingClass
                className="org.opensaml.ws.wsaddressing.impl.ReplyToUnmarshaller" />
        </ObjectProvider>

        

    </ObjectProviders>

</XMLTooling>
